# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'MVVM' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MVVM

#用最新版本
#pod 'SSZipArchive'

#指定版本
#pod 'SSZipArchive', '0.9'

    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.1.0'
    pod 'KVOController', '~> 1.2.0'
    pod 'SDWebImage', '~> 4.2.2'

  target 'MVVMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
